# Generated by Django 4.2.7 on 2023-11-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_alter_robot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='usertags',
            field=models.ManyToManyField(blank=True, to='robot.usertag'),
        ),
    ]
