# Generated by Django 4.2.7 on 2023-11-08 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("robot", "0002_robot_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="robot",
            old_name="session",
            new_name="settings",
        ),
    ]
