# Generated by Django 4.2.7 on 2023-11-21 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_post_published_alter_post_usertags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(verbose_name='Story At')),
                ('caption', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='robot.caption')),
                ('medias', models.ManyToManyField(to='robot.media', verbose_name='Story Medias')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.robot')),
                ('usertags', models.ManyToManyField(blank=True, to='robot.usertag')),
            ],
        ),
    ]
