# Generated by Django 4.2.7 on 2023-11-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robot", "0003_rename_session_robot_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="settings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
