# Generated by Django 4.2.7 on 2023-11-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robot", "0004_alter_robot_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("media_file", models.FileField(upload_to="media/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
