# Generated by Django 4.2.7 on 2023-11-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("robot", "0004_story"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="test_robot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)s",
                to="robot.robot",
            ),
        ),
    ]
