# Generated by Django 4.2.7 on 2023-11-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("robot", "0005_robot_test_robot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="test_robot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_bot",
                related_query_name="test_bot",
                to="robot.robot",
            ),
        ),
    ]
