# Generated by Django 4.2.7 on 2023-11-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robot", "0006_alter_robot_test_robot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caption",
            name="text",
            field=models.TextField(max_length=2200, verbose_name="caption"),
        ),
    ]
