version: '3'

services:
  redis:
    image: redis:latest
    restart: always

  celery-beat:
    build:
      context: .
    restart: always
    command: sh -c "celery -A instager beat -l info"
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - PRODUCTION=True
      - DB_NAME=kiwi
      - DB_USER=kiwi
      - DB_PASSWORD=kiwi
      - DB_HOST=db
      - DB_PORT=5432
  
  celery:
    build:
      context: .
    restart: always
    command: sh -c "celery -A instager worker --concurrency 3"
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - PRODUCTION=True
      - DB_NAME=kiwi
      - DB_USER=kiwi
      - DB_PASSWORD=kiwi
      - DB_HOST=db
      - DB_PORT=5432

  django:
    build:
      context: .
    command: sh -c "chmod +x /code/entrypoint.sh && /code/entrypoint.sh"
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
    environment:
      - PRODUCTION=True
      - DB_NAME=kiwi
      - DB_USER=kiwi
      - DB_PASSWORD=kiwi
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kiwi
      - POSTGRES_USER=kiwi
      - POSTGRES_PASSWORD=kiwi
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kiwi -d kiwi"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf  # Nginx production configuration file
      - ./static:/app/static  # Path to Django static files
    ports:
      - "80:80"  # Assuming Gunicorn is running on port 8000
    depends_on:
      - django

volumes:
  postgres_data:
